
package co.com.financiamiento.clienteprestamo.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SocioWsImplService", targetNamespace = "http://ws.prestamo.financiamiento.com.co/", wsdlLocation = "http://localhost:8080/SocioWsImplService/SocioWsImpl?wsdl")
public class SocioWsImplService
    extends Service
{

    private final static URL SOCIOWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOCIOWSIMPLSERVICE_EXCEPTION;
    private final static QName SOCIOWSIMPLSERVICE_QNAME = new QName("http://ws.prestamo.financiamiento.com.co/", "SocioWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SocioWsImplService/SocioWsImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOCIOWSIMPLSERVICE_WSDL_LOCATION = url;
        SOCIOWSIMPLSERVICE_EXCEPTION = e;
    }

    public SocioWsImplService() {
        super(__getWsdlLocation(), SOCIOWSIMPLSERVICE_QNAME);
    }

    public SocioWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOCIOWSIMPLSERVICE_QNAME, features);
    }

    public SocioWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SOCIOWSIMPLSERVICE_QNAME);
    }

    public SocioWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOCIOWSIMPLSERVICE_QNAME, features);
    }

    public SocioWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SocioWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SocioWs
     */
    @WebEndpoint(name = "SocioWsImplPort")
    public SocioWs getSocioWsImplPort() {
        return super.getPort(new QName("http://ws.prestamo.financiamiento.com.co/", "SocioWsImplPort"), SocioWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SocioWs
     */
    @WebEndpoint(name = "SocioWsImplPort")
    public SocioWs getSocioWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.prestamo.financiamiento.com.co/", "SocioWsImplPort"), SocioWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOCIOWSIMPLSERVICE_EXCEPTION!= null) {
            throw SOCIOWSIMPLSERVICE_EXCEPTION;
        }
        return SOCIOWSIMPLSERVICE_WSDL_LOCATION;
    }

}
